baseURL = "https://social.fernandodilland.com/"
languageCode = "es"
defaultContentLanguage = "es"

title = "Redes sociales de Fernando Dilland"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Fernando Dilland"
  headline = "Sígueme en mis redes sociales"
  image = "img/fd.png"  # path relative to static directory

  links = [
    { instagram = "https://www.instagram.com/fernandodilland/" },
    #{ email = "mailto:contacto@fernandodilland.com" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    { facebook = "https://www.facebook.com/profile.php?id=100076957804767" },
    { youtube = "https://www.youtube.com/@FernandoDilland" },
    { x = "https://x.com/fernandodilland" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/fernandodilland" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    { keybase = "https://keybase.io/fernandodilland" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://www.linkedin.com/in/fernandodilland/" },
    # { mastodon = "https://mastodon.instance/@username" },
    { medium = "https://medium.com/@fernandodilland" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/fernandodilland" },
    # { whatsapp = "https://wa.me/phone-number" },

    { link = "https://fernandodilland.com/" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
